### ISSUE TITLE
add unit tests for TimeValidator methods

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/leet-easy#31]
need unit tests for `TimeValidator`

**Comment by scopophobic** [comment]
could you please explain a bit more, I'm a newbie to open source :)

**Comment by sudiptob2** [comment]
Basically, you have to write unit test functions for `leeteasy/utils/validatiors.py`. I use `PyTest` library for unit testing you can check it out

**Comment by prakhar-198** [comment]
Please assign this issue to me I'll fix this! @sudiptob2

**Comment by sudiptob2** [comment]
> Please assign this issue to me I'll fix this! @sudiptob2

Thanks, @prakhar-198 , there is already an open PR on this issue. you can look around the code and check if there is anything you can add unit tests. I will happy to merge any unit testing.
