### ISSUE TITLE
Add retry logic if can not connect to leetcode

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/leet-easy#32]
In the current code, if `leet-easy` can not connect to `leetcode` API due to bad internet connectivity or any unknown issues, it does not retry.
Ref: [here](https://github.com/sudiptob2/leet-easy/blob/5db44e434c4306ac63bddbe207faea50e3fcd023/leeteasy/services/request_handler.py#L19)

I think a few retries would be better in such situations.

- [x] max retry: 3 times
- [x] Incremental interval ( first retry after 10 min, then 20 min, and then 30 min of sleep)

**Comment by Lainika** [comment]
Hello @sudiptob2,
I would like to take care of this issue and therefore I would appreciate if you would assign it to me.
Thank you.

**Comment by sudiptob2** [comment]
appreciated :pray: Please open a draft pull request as soon as you can after doing some changes.
