### ISSUE TITLE
Implement a github action to check unit tests

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/leet-easy#33]
A GitHub action workflow to check the unit tests.

**Comment by nilesh05apr** [comment]
Hello @sudiptob2 i am working on this task, can you please assign it to me.

**Comment by sudiptob2** [comment]
thanks @nilesh05apr, I was going to implement this myself, please make a draft PR as soon as you can and then continue further development. Also please take ref on how the workflow should look like from [here](https://github.com/sudiptob2/cf-stats/blob/main/.github/workflows/test.yml)

**Comment by nilesh05apr** [comment]
@sudiptob2 please review the commits. I have made a draft pr.

**Comment by nilesh05apr** [comment]
@sudiptob2 shall i add the code fragment for caching dependencies as same as in the cf-stats. I was using matrix for multi os testing in different python versions and sadly i don't know if we can cache dependencies in the same.

**Comment by sudiptob2** [comment]
> 
@nilesh05apr 
In the latest change, I see you have added caching, I am also not sure if it will work or not at this moment. What you can do is, run the action multiple times manually in your repo and check the output. If caching works then the output should look like the given screenshot
![image](https://user-images.githubusercontent.com/32765701/194998312-e0ddcc85-bff0-4c98-86ff-4654f8076abf.png)
