### ISSUE TITLE
Handle missed notifications if the user's machine was powered on after the scheduled time had past

### ISSUE THREAD

**Issue by sudiptob2** [sudiptob2/leet-easy#48]
At the present situation to use `leeteasy` we schedule it using cronjob at the system startup like below, ref: [docs](https://github.com/sudiptob2/leet-easy#linux-cronjob-guide)

```bash
@reboot python -m leeteasy start 14:30 &  # we scheduled the notification at 14:30
```

Now, for example, the host machine was shut down at `14:30` and the user-powered has on his device at 15:00. 
**In this case he will miss the notification for the day as it's already past 14:30.**

To handle this,
a check can be added before scheduling the Notifier. [see here](https://github.com/sudiptob2/leet-easy/blob/1690263085408cd9f799bda5e353bbfd794e1ba7/leeteasy/__main__.py#L35)

```python3
if datetime.now().time() > validated_time:
    Notifier.notify()
```
we can get the validated time from the `TimeValidator.validate(time)` Ref: [code](https://github.com/sudiptob2/leet-easy/blob/1690263085408cd9f799bda5e353bbfd794e1ba7/leeteasy/__main__.py#L33)

**Comment by QueTeddy** [comment]
Could you assign this to me?

**Comment by sudiptob2** [comment]
> Could you assign this to me?

Thanks for stopping by, :pray: please follow the [contributing guideline](https://github.com/sudiptob2/leet-easy/blob/main/docs/CONTRIBUTING.md) while making changes.

**

> Note: I have just updated the guideline don't forget to follow the latest one.

**

**Comment by QueTeddy** [comment]
so sorry I am replying late. 

So to better get the scope, am I to write a condition that just passes through if the time has lasped?

**Comment by sudiptob2** [comment]
> ```python
> if datetime.now().time() > validated_time:
>     Notifier.notify()
> ```

yes. Also, the condition will look like pretty much the above example

**Comment by Maria-Ahmed** [comment]
It looks interesting to me, please let me know if it is done? If not, assign it to me

**Comment by sudiptob2** [comment]
This issue has been implemented already
